services:
  web:
    build: .
    container_name: shop_api_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "18010:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop_api_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: shop_api_redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: shop_api_celery
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis